<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$lang = $_SESSION['lang'] ?? 'en';
if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'mr'], true)) {
    $lang = $_GET['lang'];
    $_SESSION['lang'] = $lang;
}

$translations = [
    'en' => [
        'brand_title' => 'Ahmednagar Connect',
        'brand_subtitle' => 'Taluka Officer Dashboard',
        'search_placeholder' => 'Search villages, projects, reports...',
        'notifications' => 'Notifications',
        'view_all_alerts' => 'View all alerts',
        'language' => 'Language',
        'profile_name' => 'Rajesh Deshmukh',
        'profile_role' => 'Taluka Officer',
        'my_profile' => 'My Profile',
        'settings' => 'Settings',
        'logout' => 'Logout',
        'home' => 'Home',
        'dashboard' => 'Dashboard',
        'welcome' => 'Welcome,',
        'district' => 'Ahmednagar District',
        'progress_overview' => 'Progress Overview',
        'view_all' => 'View all',
        'recent_projects' => 'Recent Projects',
        'recent_alerts' => 'Recent Alerts',
        'quick_actions' => 'Quick Actions',
        'recent_activity' => 'Recent Activity',
        'add_inspection' => 'Add Inspection',
        'upload_verification' => 'Upload Verification',
        'generate_report' => 'Generate Report',
        'view_village' => 'View Village',
        'download_pdf' => 'Download PDF',
        'project_id' => 'Project ID',
        'village' => 'Village',
        'category' => 'Category',
        'budget' => 'Budget',
        'status' => 'Status',
        'last_updated' => 'Last Updated',
        'action' => 'Action',
        'total' => 'Total',
        'done' => 'Done',
        'left' => 'Left',
        'complete' => '% complete',
        'menu_dashboard' => 'Dashboard',
        'menu_villages' => 'Village Monitoring',
        'menu_projects' => 'Project / Work Master',
        'menu_progress' => 'Progress Updates',
        'menu_gallery' => 'Photo & Document Gallery',
        'menu_finance' => 'Financial Utilization',
        'menu_verifications' => 'Pending Verifications',
        'menu_alerts' => 'Alerts & Notifications',
        'menu_reports' => 'Reports & Analytics',
        'menu_profile' => 'Profile',
        'menu_settings' => 'Settings',
    ],
    'mr' => [
        'brand_title' => 'अहमदनगर कनेक्ट',
        'brand_subtitle' => 'तालुका अधिकारी डॅशबोर्ड',
        'search_placeholder' => 'गाव, प्रकल्प, अहवाल शोधा...',
        'notifications' => 'सूचनाएँ',
        'view_all_alerts' => 'सर्व चेतावणी पहा',
        'language' => 'भाषा',
        'profile_name' => 'राजेश देशमुख',
        'profile_role' => 'तालुका अधिकारी',
        'my_profile' => 'माझे प्रोफाइल',
        'settings' => 'सेटिंग्ज',
        'logout' => 'बाहेर पडा',
        'home' => 'मुख्यपृष्ठ',
        'dashboard' => 'डॅशबोर्ड',
        'welcome' => 'स्वागत आहे,',
        'district' => 'अहमदनगर जिल्हा',
        'progress_overview' => 'प्रगती Übersicht',
        'view_all' => 'सर्व पहा',
        'recent_projects' => 'अलीकडील प्रकल्प',
        'recent_alerts' => 'अलीकडील चेतावणी',
        'quick_actions' => 'त्वरित कृती',
        'recent_activity' => 'अलीकडील क्रिया',
        'add_inspection' => 'तपासणी जोडा',
        'upload_verification' => 'व्हेरिफिकेशन अपलोड करा',
        'generate_report' => 'अहवाल तयार करा',
        'view_village' => 'गाव पहा',
        'download_pdf' => 'PDF डाउनलोड करा',
        'project_id' => 'प्रकल्प ID',
        'village' => 'गाव',
        'category' => 'श्रेणी',
        'budget' => 'बजेट',
        'status' => 'स्थिती',
        'last_updated' => 'शेवटची अद्यतनित तारीख',
        'action' => 'क्रिया',
        'total' => 'एकूण',
        'done' => 'पूर्ण',
        'left' => 'उरले',
        'complete' => '% पूर्ण',
        'menu_dashboard' => 'डॅशबोर्ड',
        'menu_villages' => 'गाव निरीक्षण',
        'menu_projects' => 'प्रकल्प / कार्य मास्टर',
        'menu_progress' => 'प्रगती अपडेट',
        'menu_gallery' => 'छायाचित्र आणि दस्तऐवज गॅलरी',
        'menu_finance' => 'आर्थिक वापर',
        'menu_verifications' => 'प्रलंबित पडताळण्या',
        'menu_alerts' => 'सतर्कता व सूचना',
        'menu_reports' => 'अहवाल आणि विश्लेषण',
        'menu_profile' => 'प्रोफाइल',
        'menu_settings' => 'सेटिंग्ज',
    ],
];

function t($key) {
    global $lang, $translations;
    return $translations[$lang][$key] ?? $translations['en'][$key] ?? $key;
}
